import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from './head'
import { Navigator } from './components/Navigator'
import { Footer } from './components/Footer'
import localFont from 'next/font/local'

const NeueHaasDisplayMediu = localFont({ src: "../assets/font/NeueHaasDisplayMediu.ttf"})
const NeueHaasDisplayLight = localFont({ src: "../assets/font/NeueHaasDisplayLight.ttf"})



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
          
      <Head />  
      
      
        
      <body style={NeueHaasDisplayLight.style} className="flex flex-col min-h-screen">
      <Navigator />  
        
        {children}
        <Footer />
        </body>
    </html>
  )
}
